### ISSUE TITLE
Research component styling

### ISSUE THREAD

**Issue by nugmanoff** [crococoders/chaikovsky#10]
As we discussed during the conf-call, we need to decide on what type of component styling will we opt for.

• https://www.sitepoint.com/react-components-styling-options/
• https://reactjs.org/docs/faq-styling.html 

You need to provide clear arguments in favor of your choice based on your research, please do not suggest something "out of thin air"

God bless you

**Comment by murattishkul** [comment]
we came up with SASS with "БЭМ" class naming methodology.
