### ISSUE TITLE
Scaffold basic Electron + TS + React boilerplate

### ISSUE THREAD

**Issue by nugmanoff** [crococoders/chaikovsky#12]
Desired result is working Electron application with minimum functionality ("Hello, World" React component would be just right). You need to setup:
• React + Typescript environment
• Some Electron boilerplate tool

Also you need to try it out yourselves so that you can briefly introduce other members of the team on how to basically code in (Electron + TS + React) environment.

P.S. You can jump straight to creating PR and working there with WIP tag, don't forget to add "Closes #12" annotation in the description of PR (for example look at  #6 )

**Comment by yerkeboolean** [comment]
Here is cool tutorial how to start with Electron + React + TypeScript + WebPack
Super easy
https://www.sitepen.com/blog/getting-started-with-electron-typescript-react-and-webpack/

**Comment by abdigali1** [comment]
I'm agree with @yerkeboolean, his tutorial is very useful, but after browsing internet, i found not better, but a few alternatives. 

[https://github.com/iRath96/electron-react-typescript-boilerplate](url) - electron react typescript boilerplate repository, which modified from awesome repo with 15k stars ([https://github.com/electron-react-boilerplate/electron-react-boilerplate](url)), but the last commit was 3 years ago.

[https://github.com/Robinfr/electron-react-typescript](url) - also awesome repo, last commit was 2, author heavily influenced with that repo with 15k stars and have husky an prettier inside. 

Also was repos like:
[https://github.com/Devtography/electron-react-typescript-webpack-boilerplate](url)
[https://github.com/lanten/electron-antd](url)
[https://github.com/Leskd/electron-react-typescript](url)

**Comment by abdigali1** [comment]
I found very useful article [https://ankitbko.github.io/2019/08/electron-forge-with-react-and-typescript/](url), where he used electron forge, react and typescript, but inside author mentioned one more article, which he was inspired by: [https://www.juhaelee.dev/typescript-electron/](url), where electron forge, react, typescript and babel is used. 
Both of them almost the same, but first one unused babel, cause he used typescript only in build time, not in development (but in the end of article he shows, how to use in also in development time), but second article used babel+typescript in development and there was a reference to "TypeScript With Babel" article([https://iamturns.com/TypeScript-babel/](url)), where describes, why you should use typescript with babel. Read it!
