### ISSUE TITLE
Configure editor setup + TSLint, Prettier

### ISSUE THREAD

**Issue by nugmanoff** [crococoders/chaikovsky#3]
Configure:
- Typescript environment
- Babel presets (ts)
- TSLint
- Prettier
- VSCode editor settings & plugins

References:
- https://github.com/anvilabs/tslint-config
- https://github.com/anvilabs/anvilabs-scripts

**Comment by murattishkul** [comment]
Hi, tslint is deprecated, people at microsoft/typescript use eslint now https://github.com/microsoft/TypeScript/issues/30553 . How about we follow them?

**Comment by murattishkul** [comment]
> Hi, tslint is deprecated, people at microsoft/typescript use eslint now [microsoft/TypeScript#30553](https://github.com/microsoft/TypeScript/issues/30553) . How about we follow them?

Folks at Palantir(tslint) and Microsoft(typescript) maintain and recommend to use typescript-eslint (https://github.com/typescript-eslint/typescript-eslint)
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by nugmanoff** [comment]
@murattishkul Yay, I didn't know that! See that's great that you took a shot on this, I'd had opt for for TSLint by default - but you did some nice researching here.

You know more than me in this topic right now, so it's your decision and it is up to you as long as you "own" the outcome of your decision! :)

Feel free to opt for the variant you think is most viable (It'd be great if you will leave here short comparison & recap of different tools you looked at after we are done)

**Comment by zhanybekovv** [comment]
Hello
