### ISSUE TITLE
Configure commit linting + Git hooks

### ISSUE THREAD

**Issue by nugmanoff** [crococoders/chaikovsky#4]
- Discuss commit convention style with @nugmanoff 
- Configure commitlint
- Configure Git hooks
- Trigger typecheck, linting, formatting, linting commits on certain hooks

References:
- https://github.com/anvilabs/commitlint-config
- https://anvilabs.co/blog/writing-practical-commit-messages/
- https://github.com/conventional-changelog/commitlint/tree/master/docs
- https://github.com/typicode/husky 
- https://github.com/aitemr/awesome-git-hooks
- https://www.atlassian.com/ru/git/tutorials/git-hooks

**Comment by abdigali1** [comment]
I recently surfed the internet for information about commit convention style. The rules, goals, motivation, changelog generating, other 7 rules to the good commit messages, about Husky, a lot of another conventions and e.t.c and nothing new. Also found another git commit messages styles guides, that are used in other frameworks like: jquery, ember, jshint (also has a images related to this) [https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/](url)
But, the most technologies prefer commit convention style (but some of them rewrite it for yourself or with the emoji)
I found the commit messages template for the VS-code ([https://github.com/nitayneeman/vscode-git-semantic-commit](url)) or to the JetBrains environment ([https://plugins.jetbrains.com/plugin/9861-git-commit-template](url)) 
Cool fact, we are going to use Electron ([https://github.com/electron/electron](url)), which is used to write in convention style, also IstanbulJs, Yargs and Karma. If you want know git deeply, you can read Pro Git book ([https://git-scm.com/book/en/v2](url))
Useful link links: 
[https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/](url)
and ofcourse [https://github.com/aitemr/awesome-git-hooks](url) (awesome всему голова)
I also watched and studied how to implement it in your project, but not already test it. 
Can you tell me what i could not write or it's okay? **@nugmanoff**

**Comment by nugmanoff** [comment]
@abdigali1 everything is ok, so we will just stick to that angular-like commit convention style.

Also I forgot to add that you should keep in mind that we need to tweak our git hooks scripts to run "smartly" - like linters & typechecking only on staged files and etc. 

Maybe consider using something like https://github.com/SamVerschueren/listr - in order to compose multiple steps of one hook into some defined process. I believe that we would need sometime soon - because we will have quite a few steps for each of the hooks.

**Comment by zhanybekovv** [comment]
As we discussed yesterday we will husky on some git hooks. Hence we need to decide which hooks we will check and how we will check. 
According to https://www.atlassian.com/ru/git/tutorials/git-hooks there are 6 different hooks {pre-commit; prepare-commit-msg; commit-msg; post-commit; post-checkout; pre-rebase }. In my opinion only first and fifth ones would be useful in project. 
Overall I am suggesting to use commitlint(https://github.com/conventional-changelog/commitlint), typechecking (https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html), eslint in the pre-commit hook. 
Post-chekout is helpful in when we are changing branches, it activates after git checkout command. 
Also can you look for this linting https://github.com/okonet/lint-staged is it same with eslint? It's usage https://www.youtube.com/watch?v=D_ka_GZoNGE

**Comment by nugmanoff** [comment]
• pre-commit -> for linting and running tests
• commit-msg -> commitlint needs to use this hook anyways

"post-checkout is helpful in when we are changing branches" - is a nice argument, but it quite not specific about how exactly is it helpful, I mean what kind of actions can we trigger on this hook

regarding _lint-staged_:
• it is basically a good practice to run linters only on currently staged files by git, because there is no need to run linters on the entire codebase every time
• I am not quite getting the reason behind this library's existence - because you can do it manually with regular scripting. But to ease it up - you can use it. It is not **not same** as ESLint, because ESLint is a **linter** and lint-staged is just a **helper script wrapper, that executes linter only on needed files**
